apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: order-api
    app: order-service
  name: order-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        api: order-api
        app: order-service
    spec:
      restartPolicy: Always
      containers:
        - image: hakktastic/demo-order-service:0.0.1
          imagePullPolicy: IfNotPresent
          name: order-service
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 500M
          startupProbe:
            httpGet:
              path: /order-service/actuator/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /order-service/actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /order-service/actuator/health/readiness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    api: order-api
    app: order-service
  name: order-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: cart-service
  ports:
    - name: "8082"
      port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30882
