apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: order-api
    app: report-service
  name: report-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        api: order-api
        app: report-service
    spec:
      restartPolicy: Always
      containers:
        - image: hakktastic/demo-report-service:0.0.1
          imagePullPolicy: Always
          name: report-service
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 500M
#          startupProbe:
#            httpGet:
#              path: /report-service/actuator/health
#              port: 8083
#            initialDelaySeconds: 120
#            periodSeconds: 5
#            failureThreshold: 10
#          livenessProbe:
#            httpGet:
#              path: /report-service/actuator/health/liveness
#              port: 8083
#            initialDelaySeconds: 60
#            periodSeconds: 5
#            failureThreshold: 10
#          readinessProbe:
#            httpGet:
#              path: /report-service/actuator/health/readiness
#              port: 8083
#            initialDelaySeconds: 60
#            periodSeconds: 5
#            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    api: order-api
    app: report-service
  name: report-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: report-service
  ports:
    - name: "8083"
      port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 30883
