apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: order-api
    app: cart-service
  name: cart-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        api: order-api
        app: cart-service
    spec:
      restartPolicy: Always
      containers:
        - image: hakktastic/demo-cart-service:0.0.1
          imagePullPolicy: IfNotPresent
          name: cart-service
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 500M
#          startupProbe:
#            httpGet:
#              path: /cart-service/actuator/health
#              port: 8081
#            initialDelaySeconds: 120
#            periodSeconds: 5
#            failureThreshold: 10
#          livenessProbe:
#            httpGet:
#              path: /cart-service/actuator/health/liveness
#              port: 8081
#            initialDelaySeconds: 60
#            periodSeconds: 5
#            failureThreshold: 10
#          readinessProbe:
#            httpGet:
#              path: /cart-service/actuator/health/readiness
#              port: 8081
#            initialDelaySeconds: 60
#            periodSeconds: 5
#            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    api: order-api
    app: cart-service
  name: cart-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: cart-service
  ports:
    - name: "8081"
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30881