apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: order-api
    app: product-service
  name: product-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        api: order-api
        app: product-service
    spec:
      restartPolicy: Always
      containers:
      - image: hakktastic/demo-product-service:0.0.1
        imagePullPolicy: IfNotPresent
        name: product-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 1
            memory: 500M
        startupProbe:
          httpGet:
            path: /product-service/actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /product-service/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /product-service/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    api: order-api
    app: product-service
  name: product-service
  namespace: default
spec:
  type: NodePort
  selector:
    service: product-service
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30880
